version: '3.7'

services:
  gt-nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - gt-web
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - static-assets:/static/

  gt-web:
    restart: always
    volumes:
      - ./src:/home/app/src
      - static-assets:/static
      - ./.sqlite3:/sqlite3

volumes:
  static-assets:
