# Generated by Django 3.1.5 on 2021-01-15 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=7, verbose_name='Vehicle plate number')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='Vehicle manufacturer')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle color')),
                ('vehicle_identification_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vehicle identification number')),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine number')),
                ('construction_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('purchage_date', models.DateTimeField(blank=True, null=True, verbose_name='Purchage date')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Entry creation date')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
                'unique_together': {('id', 'plate_number')},
            },
        ),
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone1', models.CharField(max_length=10, verbose_name='Primary phone')),
                ('phone2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Secondary phone')),
            ],
            options={
                'verbose_name': 'Vehicle owner',
                'verbose_name_plural': 'Vehicle owners',
                'db_table': 'vehicle_owner',
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleowner')),
            ],
            options={
                'verbose_name': 'Vehicle ownership',
                'verbose_name_plural': 'Vehicle ownerships',
                'db_table': 'vehicle_ownership',
                'unique_together': {('vehicle_id', 'vehicle_owner_id')},
            },
        ),
        migrations.AddField(
            model_name='vehicleowner',
            name='vehicles',
            field=models.ManyToManyField(through='vehicle.VehicleOwnership', to='vehicle.Vehicle'),
        ),
    ]
