# Generated by Django 3.2.18 on 2024-01-09 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_oil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine oil'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Construction year'),
        ),
    ]
