# Generated by Django 3.1.5 on 2021-01-15 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(verbose_name='Service description')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('travel_distance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Travel distance in kilometers')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service cost')),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Service creation date')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Entry creation date')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
    ]
