# Generated by Django 3.2.18 on 2024-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='workshop',
            field=models.TextField(blank=True, null=True, verbose_name='Workshop name'),
        ),
    ]
