# Generated by Django 3.2.18 on 2026-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='damage',
            field=models.BooleanField(default=False, verbose_name='Damage?'),
        ),
    ]
